from functools import cached_property
from typing import Generic, TypeVar

from shared.bundle_analysis import (
    BundleAnalysisReport,
    BundleAnalysisReportLoader,
)
from shared.torngit.base import TorngitBaseAdapter
from shared.yaml import UserYaml

from database.enums import ReportType
from database.models.core import Commit, Repository
from database.models.reports import CommitReport
from services.archive import ArchiveService
from services.bundle_analysis.new_notify.types import NotificationType
from services.repository import (
    get_repo_provider_service,
)
from services.storage import get_storage_client

T = TypeVar("T")


class ContextNotLoadedError(Exception):
    pass


class NotificationContextField(Generic[T]):
    """NotificationContextField is a descriptor akin to a Django model field.
    If you create one as a class member named `foo`, it will define the behavior to get and set an instance member named `foo`.
    It is also similar to @property
    """

    def __set_name__(self, owner, name) -> None:
        self._name = name

    def __get__(self, instance: "NotificationContextField", owner) -> T:
        if self._name not in instance.__dict__:
            raise ContextNotLoadedError(
                "The property you are trying to access is not loaded. Make sure to build the context before using it."
            )
        return instance.__dict__[self._name]

    def __set__(self, instance: "NotificationContextField", value: T) -> None:
        instance.__dict__[self._name] = value


class BaseBundleAnalysisNotificationContext:
    """Base NotificationContext for bundle analysis notifications.
    It includes basic information that all bundle analysis notifications need.
    Use NotificationContextBuilder to populate the context.

    Example:
      builder = NotificationContextBuilder(commit, current_yaml, GITHUB_APP_INSTALLATION_DEFAULT_NAME)
      notification_context = builder.build_context().get_result()
    """

    notification_type: NotificationType

    def __init__(
        self, commit: Commit, current_yaml: UserYaml, gh_app_installation_name: str
    ) -> None:
        self.commit = commit
        self.current_yaml = current_yaml
        self.gh_app_installation_name = gh_app_installation_name

    @cached_property
    def repository(self) -> Repository:
        return self.commit.repository

    @cached_property
    def repository_service(self) -> TorngitBaseAdapter:
        return get_repo_provider_service(
            self.repository,
            installation_name_to_use=self.gh_app_installation_name,
        )

    commit_report: CommitReport = NotificationContextField[CommitReport]()
    bundle_analysis_report: BundleAnalysisReport = NotificationContextField[
        BundleAnalysisReport
    ]()


class NotificationContextBuildError(Exception):
    def __init__(self, failed_step: str, detail: str | None = None) -> None:
        super()
        self.failed_step = failed_step
        self.detail = detail


class WrongContextBuilderError(Exception):
    pass


class NotificationContextBuilder:
    """Creates the BaseBundleAnalysisNotificationContext one step at a time, in the correct order."""

    def initialize(
        self, commit: Commit, current_yaml: UserYaml, gh_app_installation_name: str
    ) -> "NotificationContextBuilder":
        self._notification_context = BaseBundleAnalysisNotificationContext(
            commit=commit,
            current_yaml=current_yaml,
            gh_app_installation_name=gh_app_installation_name,
        )
        return self

    def is_field_loaded(self, field_name: str):
        return field_name in self._notification_context.__dict__

    def load_commit_report(self) -> "NotificationContextBuilder":
        """Loads the CommitReport into the NotificationContext
        Raises:
            NotificationContextBuildError: no CommitReport exist for the commit
        """
        if self.is_field_loaded("commit_report"):
            return self
        commit_report = self._notification_context.commit.commit_report(
            report_type=ReportType.BUNDLE_ANALYSIS
        )
        if commit_report is None:
            raise NotificationContextBuildError("load_commit_report")
        self._notification_context.commit_report = commit_report
        return self

    def load_bundle_analysis_report(self) -> "NotificationContextBuilder":
        """Loads the BundleAnalysisReport into the NotificationContext
        BundleAnalysisReport is an SQLite report generated by processing uploads
        Raises:
            NotificationContextBuildError: no BundleAnalysisReport exists for the commit.
        """
        if self.is_field_loaded("bundle_analysis_report"):
            return self
        repo_hash = ArchiveService.get_archive_hash(
            self._notification_context.repository
        )
        storage_service = get_storage_client()
        analysis_report_loader = BundleAnalysisReportLoader(storage_service, repo_hash)
        bundle_analysis_report = analysis_report_loader.load(
            self._notification_context.commit_report.external_id
        )
        if bundle_analysis_report is None:
            raise NotificationContextBuildError("load_bundle_analysis_report")
        self._notification_context.bundle_analysis_report = bundle_analysis_report
        return self

    def build_context(self) -> "NotificationContextBuilder":
        """Calls all the steps necessary to fully load the NotificationContext
        Raises:
            NotificationContextBuildError: if any of the steps fail
        """
        self.load_commit_report()
        self.load_bundle_analysis_report()
        return self

    def get_result(self) -> BaseBundleAnalysisNotificationContext:
        """Returns the NotificationContext.
        Should be called after `build_context`, or you get an empty context back.
        """
        return self._notification_context
