import sentry_sdk

from services.report.languages.base import BaseLanguageProcessor
from services.report.report_builder import ReportBuilderSession


class SimplecovProcessor(BaseLanguageProcessor):
    """
    Handles processing of coverage reports generated by Simplecov (https://github.com/simplecov-ruby/simplecov)
    The JSON formatter this processor expects is simplecov-json (https://github.com/vicentllongo/simplecov-json)

    """

    def matches_content(self, content: dict, first_line: str, name: str) -> bool:
        return isinstance(content, dict) and content.get("command_name") == "RSpec"

    @sentry_sdk.trace
    def process(
        self, content: dict, report_builder_session: ReportBuilderSession
    ) -> None:
        return from_json(content, report_builder_session)


def from_json(json: dict, report_builder_session: ReportBuilderSession) -> None:
    for data in json["files"]:
        _file = report_builder_session.create_coverage_file(data["filename"])
        if _file is None:
            continue

        # Structure depends on which Simplecov version was used so we need to handle either structure
        coverage = data["coverage"]
        coverage_to_check = (
            coverage["lines"]
            if isinstance(coverage, dict)
            and coverage.get("lines")  # Simplecov version >= 0.18
            else coverage  # Simplecov version < 0.18
        )

        for ln, cov in enumerate(coverage_to_check, start=1):
            _file.append(
                ln,
                report_builder_session.create_coverage_line(
                    cov,
                ),
            )

        report_builder_session.append(_file)
