version: 2
jobs:
  build:
    docker:
    - image: gcr.io/codecov-enterprise-sandbox/codecov-deploy:latest
      user: root
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    - image: circleci/postgres:9.6.2
    working_directory: /work
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Copy gcloud cli and auth for docker push
        command: |-
          echo "$GCLOUD_SERVICE_KEY" > service.json
          gcloud auth activate-service-account --key-file=service.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud auth configure-docker
          gcloud container clusters get-credentials --region us-east4 default-codecov-cluster
    - run:
        name: build container
        command: |-
          printenv
          make build GH_ACCESS_TOKEN=$GH_ACCESS_TOKEN VERSION=$CIRCLE_TAG
          make push
  test:
    docker:
    - image: gcr.io/codecov-enterprise-sandbox/codecov-worker:latest
      user: root
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    - image: circleci/postgres:9.6.2
    - image: redis:latest
    working_directory: /app
    steps:
    - run:
        name: run tests
        command: |
          python -m pytest --cov=./
  deploy:
    docker:
    - image: gcr.io/codecov-enterprise-sandbox/codecov-deploy:latest
      user: root
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    - image: circleci/postgres:9.6.2
    working_directory: /work
    steps:
    - setup_remote_docker
    - run:
        name: Copy gcloud cli and auth for docker push
        command: |-
          echo "$GCLOUD_SERVICE_KEY" > service.json
          gcloud auth activate-service-account --key-file=service.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud auth configure-docker
          gcloud container clusters get-credentials --region us-east4 default-codecov-cluster
    - run:
        name: deploy to k8s
        command: |-
          make tag VERSION=$CIRCLE_TAG
          make deploy VERSION=$CIRCLE_TAG
workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - test:
        filters:
          tags:
            only: /.*/
        requires:
        - build
    - deploy:
        filters:
          tags:
            only: /^phildier-.*/
          branches:
            ignore: /.*/
        requires:
        - build
        - test
