ARG REQUIREMENTS_IMAGE

FROM $REQUIREMENTS_IMAGE

ARG             RELEASE_VERSION

ENV             RELEASE_VERSION $RELEASE_VERSION

RUN             wget -q -O /usr/local/bin/berglas https://storage.googleapis.com/berglas/0.5.0/linux_amd64/berglas && \
                chmod +x /usr/local/bin/berglas

RUN             apt-get install gnupg
RUN             apt-get install curl

USER            codecov

COPY            . /worker
WORKDIR         /worker
