name: "Patch typing check"

on:
  push:
    branches:
      - main
      - staging
  pull_request:
  merge_group:

jobs:
  patch-typing-check:
    name: Run Patch Type Check
    uses: codecov/gha-workflows/.github/workflows/mypy.yml@00043f8fbe820934312f7fade4ea72ea92231b5e
    with:
      extra_config: "--explicit-package-bases"
